### ISSUE TITLE
USB 2.0 capture

### ISSUE THREAD

**Issue by DedupOperator** [SterlingButters/ip-kvm-interface#1]
Hey @SterlingButters I have just visited your repo, nice progress.
I don't really understand your schema.

1) The schema looks like HDMI _output_ from the LinkStable device is going into the HDMI _output_ of the RaspberryPI.
How are you routing this exactly?

2) The LinkStable USB 3.0 HD Game Capture Card amazon link states:
"The video capture device requires a USB 3.0 port (or higher), does not work with USB 2.0 ports (or lower)."
Did you succeed feeding the encoded stream into the RaspberryPI board?

**Comment by SterlingButters** [comment]
Wow, thanks for pointing that out, I just got carried away with the connections there I guess - I will fix it today. There is actually supposed to be a TV screen on the schematic that accepts HMDI out from both RPi3 and PC as inputs.

**Comment by SterlingButters** [comment]
And I can tell you that from using FMstrat’s repo that the LinkStable capture device works with RPi3 so not sure how it’s working based on that documentation you found but it does work

**Comment by SterlingButters** [comment]
Feel free to reopen this issue if you end up not being able to use the LinkStable for some reason
